trigger:
  branches:
    include:
    - master # Adjust the branch name according to your repository's default branch

variables:
  acrName: 'acr234346'
  imageName: 'crypt-react-app'
  k8sNamespace: 'default'
  k8sDeploymentName: 'k8s-deployment'

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - task: Docker@2
      displayName: 'Login to ACR'
      inputs:
        containerRegistry: 'docker-reg'
        command: 'login'

    - task: Docker@2
      displayName: 'Build and Push Docker image'
      inputs:
        containerRegistry: 'docker-reg'
        repository: '$(acrName).azurecr.io/$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(Build.BuildId)'

- stage: Deploy
  displayName: 'Deploy stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: 'Deploy Job'
    environment: 'production'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:

          - task: Kubernetes@1
            displayName: 'Deploy to AKS'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'k8s-con'
              namespace: 'default'
              command: 'apply'
              useConfigurationFile: true
              configuration: |
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: $(k8sDeploymentName)
                  namespace: $(k8sNamespace)
                spec:
                  replicas: 1
                  selector:
                    matchLabels:
                      app: $(k8sDeploymentName)
                  template:
                    metadata:
                      labels:
                        app: $(k8sDeploymentName)
                    spec:
                      containers:
                      - name: $(imageName)
                        image: $(acrName).azurecr.io/$(imageName):$(Build.BuildId)
                        ports:
                        - containerPort: 80
              secretType: 'dockerRegistry'
              containerRegistryType: 'Azure Container Registry'
