apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-app
  template:
    metadata:
      labels:
        app: crypto-app
    spec:
      containers:
      - name: $(imageName)
        image: $(acrName).azurecr.io/$(imageName):$(Build.BuildId)
        ports:
        - containerPort: 80
