apiVersion: v1
kind: Service
metadata:
  name: crypto-app-service
  namespace: default
spec:
  selector:
    app: crypto-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
